version: '3.3'

services:
  postgres:
    image: postgres:13
    # environment:
    #   - POSTGRES_DB=my_db
    #   - POSTGRES_USER=josedev
    #   - POSTGRES_PASSWORD=admin123
    # In the file set variables just like here! ;D
    env_file:
      - db.env
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    # environment:
    #   - PGADMIN_DEFAULT_EMAIL=admin@mail.com
    #   - PGADMIN_DEFAULT_PASSWORD=root
    env_file:
      - db.env
    ports:
      - 5050:80


